server:
  port: 1202
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${SPRINGCLOUD_REGISTRY_ADDRESS}
    healthcheck:
      enabled: true
    lease:
      duration: 5