spring:
  application:
    name: tesla-grpc
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://tesla-mysql:3306/gateway?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
server:
  port: 9000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:META-INF/mybatis/**/*Mapper.xml
saluki:
  grpc:
    registryAddress: consul:8500
dubbo:
  registryAddress: zookeeper://zookeeper:2181
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://eureka.springcloud.cn/eureka/